"""add rate limiting and idempotency fields

Revision ID: 49e8dc8ded41
Revises: 000000000003
Create Date: 2025-11-12 21:52:54.834352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e8dc8ded41'
down_revision = '000000000003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_codes', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('auth_codes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auth_codes', sa.Column('attempts', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_auth_codes_created_at'), 'auth_codes', ['created_at'], unique=False)
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.add_column('payments', sa.Column('intent_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_intent_id'), 'payments', ['intent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_intent_id'), table_name='payments')
    op.drop_column('payments', 'intent_id')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_column('orders', 'idempotency_key')
    op.drop_index(op.f('ix_auth_codes_created_at'), table_name='auth_codes')
    op.drop_column('auth_codes', 'attempts')
    op.drop_column('auth_codes', 'created_at')
    op.drop_column('auth_codes', 'ip_address')
    # ### end Alembic commands ###