"""add email to auth_codes for rate limiting

Revision ID: b5d90b87eda2
Revises: 49e8dc8ded41
Create Date: 2025-11-12 22:06:47.065176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5d90b87eda2'
down_revision = '49e8dc8ded41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_codes', sa.Column('email', sa.String(length=255), nullable=False))
    op.alter_column('auth_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_auth_codes_email'), 'auth_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_codes_email'), table_name='auth_codes')
    op.alter_column('auth_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('auth_codes', 'email')
    # ### end Alembic commands ###