name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/backend/requirements.txt

      - name: Run Python tests
        run: |
          cd apps/backend
          pytest

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name's Install Node.js dependencies
        run: |
          cd apps/web
          npm install

      - name: Build web app
        run: |
          cd apps/web
          npm run build
